"""Turn the app marts into one JSON file a static page can read.

The web page is published on GitHub Pages, which serves files and runs no
Python, so the page cannot query a database and cannot call SEAP. This module
is the seam: ``bidscout export`` scores the landing database, builds the
warehouse with dbt, and writes the ``app`` marts into a single file. It reads
no other table (``bidscout.warehouse.APP_MARTS``).

Two rules shape the payload.

**Ground rule 1 — anything bidscout claims, Gabriel must be able to check.**
The file carries its own provenance (which database, which warehouse, which
profile, which rule set, when) and every verdict travels with the buyer's
sentence and the Section 3 field it came from. The page therefore never says
more than the export can justify, and the whole file is regenerated by one
command.

**Money is a string, never a JSON number.** ``json`` reads 2700000.00 back as a
float, and a float is no longer the figure the buyer wrote. Every amount goes
through ``_money``, which refuses a float outright rather than quietly rounding
a hard gate.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

from bidscout import __version__
from bidscout.decide.rules import RuleSet
from bidscout.models import Decision
from bidscout.pipeline import score_stored
from bidscout.store.db import Store
from bidscout.warehouse import APP_MARTS, read_app_marts, transform

#: Bumped when the shape changes in a way the page must handle. The page reads
#: it and says so plainly rather than rendering a file it does not understand.
#: Fields added alongside the existing ones do not bump it.
SCHEMA_VERSION = 1

#: Profile keys that hold money. Everything else is copied through untouched.
_MONEY_SUFFIX = "_ron"


def _money(value: Any) -> str | None:
    """Return a money value as an exact string, or None.

    A float is refused. By the time a sum is a float it has already stopped
    being the number the buyer wrote, and this project's whole claim is that
    its figures can be traced back to a sentence.
    """
    if value is None or value == "":
        return None
    if isinstance(value, float):
        raise TypeError(
            f"refusing to export {value!r} as money: it is a float and no longer exact. "
            "Keep it as a Decimal or a string from the database onwards."
        )
    if isinstance(value, Decimal | int | str):
        return str(value)
    raise TypeError(f"cannot export {value!r} as money")


def _profile_for_display(profile: dict[str, Any]) -> dict[str, Any]:
    """Copy the profile with its money as strings.

    Whatever is in this dict ends up on a public page when the file is
    committed, so the command prints the path it wrote and the page names the
    profile it came from. Nothing is invented and nothing is hidden.
    """
    out: dict[str, Any] = {}
    for key, value in profile.items():
        out[key] = _money(value) if key.endswith(_MONEY_SUFFIX) else value
    return out


def _when(value: Any) -> str | None:
    """A timestamp from the warehouse as ISO 8601 text, or None."""
    if value is None:
        return None
    return value.isoformat() if hasattr(value, "isoformat") else str(value)


def _tender(
    row: dict[str, Any], reasons: list[dict[str, Any]], requirements: list[dict[str, Any]]
) -> dict[str, Any]:
    """One row of ``app_tenders`` as the page reads it, with its reasons and quotes."""
    return {
        "c_notice_id": row["c_notice_id"],
        "notice_no": row["notice_no"],
        "title": row["title"],
        "buyer": row["buyer"],
        "buyer_key": row["buyer_key"],
        "cpv": row["cpv"],
        "cpv_name": row["cpv_name"],
        "notice_kind": row["notice_kind"],
        "procedure_type": row["procedure_type"],
        "contract_type": row["contract_type"],
        "estimated_value_ron": _money(row["estimated_value_ron"]),
        "published_at": _when(row["published_at"]),
        "deadline_at": _when(row["deadline_at"]),
        "has_lots": bool(row["has_lots"]),
        "is_simplified": bool(row["is_simplified"]),
        "documents": int(row["documents"]),
        "decision": row["decision"],
        "score": row["score"],
        "reasons": [
            {
                "text": reason["reason_text"],
                "quote": reason["quote"],
                "source_field": reason["source_field"],
                # pass / fail / unknown / absent, straight from the engine. The
                # page marks each gate from this, never by reading the English.
                "outcome": reason["outcome"],
            }
            for reason in sorted(reasons, key=lambda reason: reason["reason_index"])
        ],
        "unresolved": list(row["unresolved"] or []),
        "requirements": [
            {
                "kind": req["requirement_kind"],
                # The text exactly as stored, never the DECIMAL column, so the
                # page shows the figure the extractor read and nothing rounded.
                "amount": _money(req["amount_text"]),
                "currency": req["currency"],
                "quote": req["quote"],
                "source_field": req["source_field"],
                "confidence": req["confidence"],
            }
            for req in sorted(requirements, key=lambda req: req["requirement_kind"])
        ],
    }


def _unread(row: dict[str, Any]) -> dict[str, Any]:
    """A notice with no verdict, and the reason it has none."""
    return {
        "c_notice_id": row["c_notice_id"],
        "notice_no": row["notice_no"],
        "title": row["title"],
        "buyer": row["buyer"],
        "cpv": row["cpv"],
        "notice_kind": row["notice_kind"],
        "estimated_value_ron": _money(row["estimated_value_ron"]),
        "published_at": _when(row["published_at"]),
        "deadline_at": _when(row["deadline_at"]),
        "read_status": row["read_status"],
    }


def _newest_first(row: dict[str, Any]) -> tuple[str, str]:
    return (_when(row["published_at"]) or "", row["c_notice_id"])


def build_payload(
    store: Store,
    profile: dict[str, Any],
    rules: RuleSet,
    cpv_prefix: str | None = None,
    today: datetime | None = None,
    source: dict[str, str] | None = None,
    warehouse: str | Path | None = None,
) -> dict[str, Any]:
    """Score, build the warehouse, and return what the page needs as plain data.

    Three steps, always together, so an export can never show a verdict older
    than the extractor that produced it:

    1. ``score_stored`` re-reads every stored Section 3 and writes the verdicts
       and the requirements trace to the landing database.
    2. ``transform`` runs ``dbt build`` over landing: the models and their data
       tests. A broken contract stops here, before the page sees it.
    3. The ``app`` marts are read, and nothing else.
    """
    company = _profile_for_display(profile)  # refuses a float before any work is done
    company_name = str(profile.get("company_name", "default"))

    score_stored(store, profile, rules, cpv_prefix=cpv_prefix, today=today)
    built = transform(store.path, warehouse, company=company_name)
    marts = read_app_marts(built)

    rows = marts["app_tenders"]
    if cpv_prefix:
        rows = [row for row in rows if (row["cpv"] or "").startswith(cpv_prefix)]

    reasons: dict[str, list[dict[str, Any]]] = {}
    for reason in marts["app_tender_reasons"]:
        reasons.setdefault(reason["c_notice_id"], []).append(reason)
    requirements: dict[str, list[dict[str, Any]]] = {}
    for req in marts["app_tender_requirements"]:
        requirements.setdefault(req["c_notice_id"], []).append(req)

    # Highest score first; within a score, newest first, as the scorer orders.
    scored = sorted(
        (row for row in rows if row["read_status"] == "scored"), key=_newest_first, reverse=True
    )
    scored.sort(key=lambda row: row["score"], reverse=True)
    tenders = [
        _tender(row, reasons.get(row["c_notice_id"], []), requirements.get(row["c_notice_id"], []))
        for row in scored
    ]
    unread = sorted(
        (row for row in rows if row["read_status"] != "scored"), key=_newest_first, reverse=True
    )

    decisions = [tender["decision"] for tender in tenders]
    return {
        "schema": SCHEMA_VERSION,
        "generated_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "bidscout_version": __version__,
        "source": {**(source or {}), "warehouse": _display_path(built)},
        # Where every row on the page came from: docs/data-model.md.
        "pipeline": {
            "portal": "https://www.e-licitatie.ro/api-pub/",
            "marts": [f"app.{name}" for name in APP_MARTS],
            "read_status": {
                row["read_status"]: int(row["notices"]) for row in marts["app_pipeline_status"]
            },
        },
        "company": company,
        "rules": {
            "name": rules.name,
            "go_threshold": rules.go_threshold,
            "gates": [
                {"kind": gate.kind, "profile_key": gate.profile_key, "label": gate.label}
                for gate in rules.gates
            ],
            "weights": dict(rules.weights),
        },
        "totals": {
            "scored": len(tenders),
            "skipped_unread": len(unread),
            "go": decisions.count(Decision.GO.value),
            "check": decisions.count(Decision.CHECK.value),
            "no_go": decisions.count(Decision.NO_GO.value),
        },
        "tenders": tenders,
        # Shown on the page on purpose. A notice nobody has read in full is not
        # a notice without requirements, and hiding the skipped ones would make
        # the page look more complete than the database is. `read_status` says
        # why each one has no verdict.
        "skipped": [_unread(row) for row in unread],
    }


def _display_path(path: Path) -> str:
    """A path relative to the working directory when it is under it, with forward slashes.

    The file is published, so it should say ``data/demo.duckdb`` and not the
    absolute path of somebody's home directory.
    """
    try:
        path = path.resolve().relative_to(Path.cwd().resolve())
    except ValueError:
        pass
    return path.as_posix()


def write_export(path: str | Path, payload: dict[str, Any]) -> Path:
    """Write the payload as formatted UTF-8 JSON and return the path.

    ``allow_nan=False`` is deliberate: NaN and Infinity are not JSON, and a
    browser's ``JSON.parse`` rejects them. Better to fail here than to publish
    a page that silently will not load.
    """
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    return target
