"""Turn the scored database into one JSON file a static page can read.

The web page is published on GitHub Pages, which serves files and runs no
Python, so the page cannot query SQLite and cannot call SEAP. This module is
the seam: ``bidscout export`` scores the database offline and writes
everything the page needs into a single file.

Two rules shape the payload.

**Ground rule 1 — anything bidscout claims, Gabriel must be able to check.**
The file carries its own provenance (which database, which profile, which rule
set, when) and every verdict travels with the buyer's sentence and the Section 3
field it came from. The page therefore never says more than the export can
justify, and the whole file is regenerated by one command.

**Money is a string, never a JSON number.** ``json`` reads 2700000.00 back as a
float, and a float is no longer the figure the buyer wrote. Every amount goes
through ``_money``, which refuses a float outright rather than quietly rounding
a hard gate.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

from bidscout import __version__
from bidscout.decide.rules import RuleSet
from bidscout.models import Decision, Notice, Verdict
from bidscout.pipeline import score_stored
from bidscout.store.db import Store

#: Bumped when the shape changes in a way the page must handle. The page reads
#: it and says so plainly rather than rendering a file it does not understand.
SCHEMA_VERSION = 1

#: Profile keys that hold money. Everything else is copied through untouched.
_MONEY_SUFFIX = "_ron"


def _money(value: Any) -> str | None:
    """Return a money value as an exact string, or None.

    A float is refused. By the time a sum is a float it has already stopped
    being the number the buyer wrote, and this project's whole claim is that
    its figures can be traced back to a sentence.
    """
    if value is None or value == "":
        return None
    if isinstance(value, float):
        raise TypeError(
            f"refusing to export {value!r} as money: it is a float and no longer exact. "
            "Keep it as a Decimal or a string from the database onwards."
        )
    if isinstance(value, Decimal | int | str):
        return str(value)
    raise TypeError(f"cannot export {value!r} as money")


def _profile_for_display(profile: dict[str, Any]) -> dict[str, Any]:
    """Copy the profile with its money as strings.

    Whatever is in this dict ends up on a public page when the file is
    committed, so the command prints the path it wrote and the page names the
    profile it came from. Nothing is invented and nothing is hidden.
    """
    out: dict[str, Any] = {}
    for key, value in profile.items():
        out[key] = _money(value) if key.endswith(_MONEY_SUFFIX) else value
    return out


def _tender(notice: Notice, verdict: Verdict, requirements: list[dict[str, Any]]) -> dict[str, Any]:
    """One row of the ranked list, with everything the detail view shows."""
    return {
        "c_notice_id": notice.c_notice_id,
        "notice_no": notice.notice_no,
        "title": notice.title,
        "buyer": notice.buyer,
        "cpv": notice.cpv,
        "estimated_value_ron": _money(notice.estimated_value_ron),
        "published_at": notice.published_at,
        "deadline_at": notice.deadline_at,
        "has_lots": notice.has_lots,
        "is_simplified": notice.is_simplified,
        "decision": verdict.decision.value,
        "score": verdict.score,
        "reasons": [
            {
                "text": r.text,
                "quote": r.quote,
                "source_field": r.source_field,
                # pass / fail / unknown / absent, straight from the engine. The
                # page marks each gate from this, never by reading the English.
                "outcome": r.outcome,
            }
            for r in verdict.reasons
        ],
        "unresolved": list(verdict.unresolved),
        "requirements": requirements,
    }


def build_payload(
    store: Store,
    profile: dict[str, Any],
    rules: RuleSet,
    cpv_prefix: str | None = None,
    today: datetime | None = None,
    source: dict[str, str] | None = None,
) -> dict[str, Any]:
    """Score the database and return everything the page needs, as plain data.

    Scoring happens here rather than being read from the ``scores`` table so
    that an export can never show a verdict older than the extractor that
    produced it. The requirements trace is read straight afterwards, which is
    what lets the page quote the buyer without re-running the parser.
    """
    run = score_stored(store, profile, rules, cpv_prefix=cpv_prefix, today=today)

    tenders: list[dict[str, Any]] = []
    for notice, verdict in run.verdicts:
        requirements = [
            {
                "kind": req.kind,
                "amount": _money(req.amount),
                "currency": req.currency,
                "quote": req.quote,
                "source_field": req.source_field,
                "confidence": req.confidence.value,
            }
            for req in store.requirements(notice.c_notice_id)
        ]
        tenders.append(_tender(notice, verdict, requirements))

    decisions = [tender["decision"] for tender in tenders]
    return {
        "schema": SCHEMA_VERSION,
        "generated_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "bidscout_version": __version__,
        "source": source or {},
        "company": _profile_for_display(profile),
        "rules": {
            "name": rules.name,
            "go_threshold": rules.go_threshold,
            "gates": [
                {"kind": gate.kind, "profile_key": gate.profile_key, "label": gate.label}
                for gate in rules.gates
            ],
            "weights": dict(rules.weights),
        },
        "totals": {
            "scored": len(tenders),
            "skipped_unread": len(run.skipped_unread),
            "go": decisions.count(Decision.GO.value),
            "check": decisions.count(Decision.CHECK.value),
            "no_go": decisions.count(Decision.NO_GO.value),
        },
        "tenders": tenders,
        # Shown on the page on purpose. A notice nobody has read in full is not
        # a notice without requirements, and hiding the skipped ones would make
        # the page look more complete than the database is.
        "skipped": [
            {
                "c_notice_id": notice.c_notice_id,
                "notice_no": notice.notice_no,
                "title": notice.title,
                "buyer": notice.buyer,
                "published_at": notice.published_at,
            }
            for notice in run.skipped_unread
        ],
    }


def write_export(path: str | Path, payload: dict[str, Any]) -> Path:
    """Write the payload as formatted UTF-8 JSON and return the path.

    ``allow_nan=False`` is deliberate: NaN and Infinity are not JSON, and a
    browser's ``JSON.parse`` rejects them. Better to fail here than to publish
    a page that silently will not load.
    """
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    return target
